### ISSUE TITLE
"University of Wollongong" in template.docx properties

### ISSUE THREAD

**Issue by ntrlshrp** [benmarwick/rrtools#125]
**Describe the bug**
This is very minor. The current default output is 

```
output: 
    bookdown::word_document2:
      fig_caption: yes
      reference_docx: "../templates/template.docx" # Insert path for the DOCX file
      pandoc_args:
      - --lua-filter=../templates/scholarly-metadata.lua
      - --lua-filter=../templates/author-info-blocks.lua
      - --lua-filter=../templates/pagebreak.lua
```
This uses `../templates/template.docx`, which has custom properties that do not come from the `.Rmd`/user that are added to the output document, `paper.docx`.

These are: 
`AppVersion: 14.0000`
`Company: University of Wollongong`
etc.

**To Reproduce**
Describe the steps to reproduce the behavior:
1. Do `rrtools::create_compendium("DELETEme01")`
2. Click on `Knit`
3. Review `File > Properties > Custom Properties` of the output `paper.docx`

*NOTE: One can also reproduce the issue using `Dockerfile`, e.g., `R -e "rmarkdown::render('/DELETEme01/analysis/paper/paper.Rmd')"`.

**Expected behavior**
The output document should not include any custom (or non-generic) properties that do not come from the `.Rmd`/user.
